version: '2'
services:
    transport-app:
        image: transport
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://transport-postgresql:5432/transport
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    transport-postgresql:
        extends:
            file: postgresql.yml
            service: transport-postgresql
